language: php
sudo: true
php:
    - 7.0

services:
  - mysql

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - \curl -L https://get.rvm.io | bash -s stable
  - /bin/bash -l -c "rvm requirements"
  - /bin/bash -l -c "rvm install 2.0"
  - /bin/bash -l -c "gem install bundler --no-ri --no-rdoc"
  - travis/install-nginx.sh
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log
  - mkdir typo3test
  - cd typo3test
  - git init
  - echo "vendor" >> .gitignore
  - curl -sSL https://raw.githubusercontent.com/Lingewoud/capistrano-typo3/master/install.sh | sh
  - git add .
  - git commit -m "install" -a
  - git status
  - ls
  - ./bin/cap -T
