language: php
sudo: false
php:
    - 7.0
rvm:
  - 2.4.1

services:
  - mysql

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - travis/install-nginx.sh
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log
  - mkdir typo3test
  - cd typo3test
  - git init
  - echo "vendor" >> .gitignore
  - curl -sSL https://raw.githubusercontent.com/Lingewoud/capistrano-typo3/master/install.sh | sh
  - git add .
  - git commit -m "install" -a
  - git status
  - ls
  - echo "jo"
