language: ruby
sudo: false
php:
    - 7.0
rvm:
  - 2.4.1

services:
  - mysql

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  #  - dpkg -l | grep php
  #- dpkg -l | grep nginx
  - apt-get install -y apache2 libapache2-mod-fastcgi php-memcached php-memcache php-apcu php7.0
  - apt-get install -y php7.0-mcrypt php7.0-mysql php7.0-xml php7.0-fpm php7.0-xml php7.0-soap
  - apt-get install -y php7.0-zip php7.0-mbstring php7.0-gd php7.0-opcache graphicsmagick
  - dpkg -l
  - travis/install-nginx.sh
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log
  - mkdir typo3test
  - cd typo3test
  - git init
  - echo "vendor" >> .gitignore
  - curl -sSL https://raw.githubusercontent.com/Lingewoud/capistrano-typo3/master/install.sh | sh
  - git add .
  - git commit -m "install" -a
  - git status
  - ls
  - echo "jo"
