language: php
sudo: false
php:
    - 7.0
services:
  - mysql

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - travis/install-nginx.sh
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

script:
  - curl -vsf 'http://localhost:8080/hello.php' &> /dev/stdout
  - cat /tmp/error.log
  - mkdir typo3test
  - cd typo3test && git init
  - cd typo3test && curl -sSL https://raw.githubusercontent.com/Lingewoud/capistrano-typo3/master/install.sh | sh
  - cd typo3test && git add .
  - cd typo3test && git commit -m "install"
  - cd typo3test && git status

